version: "3.2"
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: "wiki"
      POSTGRES_PASSWORD: "wikijsrocks"
      POSTGRES_USER: "wikijs"
    networks:
      - ultron-net  
    volumes:
      - /docker_dir/db-data:/var/lib/postgresql/data  
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://10.111.22.175:1514"
        syslog-format: "rfc5424micro"
        tag: "psql-dev-1.0.0"
    deploy:   
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.ENV==MANAGER]
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "datainfo@123.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2019!"
    ports:
      - "16543:80"
    networks:
      - ultron-net   
    depends_on:
      - db
    volumes:
       - /docker_dir/pgadmin:/var/lib/pgadmin
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://10.111.22.175:1514"
        syslog-format: "rfc5424micro"
        tag: "pgadmin-1.0.0"
    deploy:   
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.ENV==MANAGER]    
  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: "wikijs"
      DB_PASS: "wikijsrocks"
      DB_NAME: "wiki"
    ports:
      - "1088:3000"
    networks:
      - ultron-net   
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://10.111.22.175:1514"
        syslog-format: "rfc5424micro"
        tag: "wiki-1.0.0"
    deploy:   
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.labels.ENV==MANAGER]  


networks:
  ultron-net:
    external: true  